version: '3'

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
    volumes:
      - /opt/caddy/Caddyfile:/etc/Caddyfile
      - /opt/caddy/ssl:/root/.caddy
    restart: unless-stopped
  wordpress_db:
    image: mariadb:latest
    volumes:
      - /opt/wp/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "wedding_site"
      MYSQL_USER: "wedding"
      MYSQL_PASSWORD: ""
  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    volumes:
      - /opt/wp/wp-content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_USER: "wedding"
      WORDPRESS_DB_HOST: "wordpress_db"
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: "wedding_site"
  wedding_manager_db:
    image: "postgres:latest"
    restart: unless-stopped
    environment:
      POSTGRES_DB: wedding-manager-db
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: wedding_manager
    volumes:
      - /opt/wedding_manager/postgres:/var/lib/postgres
  wedding_manager_api:
    image: "wedding-manager:latest"
    restart: unless-stopped
    depends_on:
      - wedding_manager_db
    environment:
      FLASK_APP: "run.py"
      FLASK_SECRET: ""
      APP_ENV: "production"
      DATABASE_URI: "postgresql://wedding_manager:@wedding_manager_db/wedding-manager-db"
      TWILIO_AUTH_TOKEN: ""